---
title: "nicetable Vignette"
author: "Lisa Rein"
date: "Wednesday, August 19, 2015"
output: html_document
---

```{r load_package}

library(devtools)
install_github("lisaerein/nicetable")
library(nicetable)

library(datasets)
iris <- iris
iris$color <- sample(c("white", "pink", "red"), nrow(iris), replace = T)

require(knitr)
options(width = 120)
opts_chunk$set(base.dir = "r_code", 
               fig.path = "figures/",
               message=FALSE,
               warning=FALSE,
               results='asis',
               fig.height = 4,
               fig.width = 9)

```

### Basic single group summary table
```{r}

table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2))

```

#### change number of decimal places
```{r}
table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2),
                    cont.dec = 1,
                    perc.dec = 2)
```

#### change summary statistics for continuous variables & add missing frequency
```{r, results = 'asis'}
table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2),
                    stats = "median_range")
```

#### change variable labels
```{r, results = 'asis'}
table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2),
                    labels = c("Sepal Length",
                               "Sepal Width",
                               "Petal Length",
                               "Petal Width",
                               "Flower Species",
                               "Color"))
```

#### change look of the table using htmlTable
```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2),
                    htmlTable = TRUE)
```

```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris),
                    type = c(1,1,1,1,2,2),
                    htmlTable = TRUE,
                    color = "#99CCFF")
```

### Stratified summary table

```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris)[c(1:4,6)],
                    by = "Species",
                    type = c(1,1,1,1,2))

```

#### Add parametric tests

```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris)[c(1:4,6)],
                    by = "Species",
                    type = c(1,1,1,1,2),
                    tests = "np")

```

#### Change statistical tests by variable

```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris)[c(1:4,6)],
                    by = "Species",
                    type = c(1,1,1,1,2),
                    tests = c("ttest", "kw", "anova", NA, "fe"))

```

#### Remove "All" column

```{r, results = 'asis'}

table1 <- nicetable(df = iris,
                    covs = names(iris)[c(1:4,6)],
                    by = "Species",
                    type = c(1,1,1,1,2),
                    allcol = FALSE)

```
